/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package prepa26022526.pkg2;

import EDD.ABB;

/**
 *
 * @author Nicola
 */
public class InterfazGUI extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(InterfazGUI.class.getName());
    public ABB miArbol = new ABB();

    /**
     * Creates new form InterfazGUI
     */
    public InterfazGUI() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CargarNumeros = new javax.swing.JButton();
        numeros = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Recorrido = new javax.swing.JTextArea();
        MostrarPreOrder = new javax.swing.JButton();
        MostrarPostOrder = new javax.swing.JButton();
        MostrarInOrder = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        CargarPostOrder = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CargarNumeros.setText("Cargar Numeros");
        CargarNumeros.addActionListener(this::CargarNumerosActionPerformed);

        numeros.addActionListener(this::numerosActionPerformed);

        Recorrido.setColumns(20);
        Recorrido.setRows(5);
        jScrollPane1.setViewportView(Recorrido);

        MostrarPreOrder.setText("PreOrder");
        MostrarPreOrder.addActionListener(this::MostrarPreOrderActionPerformed);

        MostrarPostOrder.setText("PostOrder");
        MostrarPostOrder.addActionListener(this::MostrarPostOrderActionPerformed);

        MostrarInOrder.setText("InOrder");
        MostrarInOrder.addActionListener(this::MostrarInOrderActionPerformed);

        jButton1.setText("Vaciar Arbol");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        CargarPostOrder.setText("Cargar via PostOrder");
        CargarPostOrder.addActionListener(this::CargarPostOrderActionPerformed);

        jButton2.setText("Cargar via PreOrder");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(numeros, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MostrarPostOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(MostrarInOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MostrarPreOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CargarPostOrder))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CargarNumeros)
                            .addComponent(jButton2))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CargarNumeros)
                    .addComponent(numeros, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CargarPostOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MostrarPreOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MostrarPostOrder)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MostrarInOrder)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CargarNumerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarNumerosActionPerformed
        // TODO add your handling code here:

        String[] misNumeros = this.numeros.getText().split(",");

        for (int i = 0; i < misNumeros.length; i++) {
            if (misNumeros[i].strip() != "") {
                miArbol.insertar(Integer.parseInt(misNumeros[i].strip()));
            }
        }
        this.numeros.setText("");
    }//GEN-LAST:event_CargarNumerosActionPerformed

    private void numerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numerosActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_numerosActionPerformed

    private void MostrarPreOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPreOrderActionPerformed
        // TODO add your handling code here:
        this.Recorrido.setText(this.miArbol.PreOrder());

    }//GEN-LAST:event_MostrarPreOrderActionPerformed

    private void MostrarPostOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarPostOrderActionPerformed
        // TODO add your handling code here:
        this.Recorrido.setText(this.miArbol.PostOrder());
    }//GEN-LAST:event_MostrarPostOrderActionPerformed

    private void MostrarInOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostrarInOrderActionPerformed
        // TODO add your handling code here:

        this.Recorrido.setText(this.miArbol.InOrder());
    }//GEN-LAST:event_MostrarInOrderActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.miArbol = new ABB();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        String[] misNumeros = this.numeros.getText().split(",");

        for (int i = 0; i < misNumeros.length; i++) {
            if (misNumeros[i].strip() != "") {
                miArbol.insertar(Integer.parseInt(misNumeros[i].strip()));
            }
        }
        this.numeros.setText("");


    }//GEN-LAST:event_jButton2ActionPerformed

    private void CargarPostOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CargarPostOrderActionPerformed
        // TODO add your handling code here:

        String[] misNumeros = this.numeros.getText().split(",");

        for (int i = misNumeros.length - 1; i >= 0; i--) {
            if (misNumeros[i].strip() != "") {
                miArbol.insertar(Integer.parseInt(misNumeros[i].strip()));
            }
        }
        this.numeros.setText("");
    }//GEN-LAST:event_CargarPostOrderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new InterfazGUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CargarNumeros;
    private javax.swing.JButton CargarPostOrder;
    private javax.swing.JButton MostrarInOrder;
    private javax.swing.JButton MostrarPostOrder;
    private javax.swing.JButton MostrarPreOrder;
    private javax.swing.JTextArea Recorrido;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField numeros;
    // End of variables declaration//GEN-END:variables
}
